language: node_js
node_js: node
before_script:
- npm install -g gitbook-cli
script: 
- gitbook install
- gitbook build
- cp icons/* _book/gitbook/images
deploy:
  local_dir: _book
  provider: pages
  skip_cleanup: true
  name: Travis Build Bot
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
  # committer_from_gh: true
  # allow_empty_commit: true
  github_token:
    secure: ZutxqsWgkleoYtyvMna47NJr1g1NAJPy/HrJ86wQ8XgWfVClSrFt3zHJTiVJWRwgFQBGmkEMtJ2ZVtrQ9p8smLNiJVmt23cJf6KGu7vDs9dBPT4HLnWEQ3WjL3hZD0i4f+avqA1X7q63rWPwdSQUiBMntCwlrF55sGUa0dCGJZynkS4oMjCFLdrft7QrW3FIO5+t6C6YC9cp1JwTqX6gsHPTvDq0TsiGKNyN+tRV82r3ySVdKxZtDA80ifWfObNCS+JB4JF1Oca1rmPmPyKOO/RZrD4jzbShSEN84eN0HxYmkk+nsMVy/0HAGT/zLpQigVOqguWwwhEw1AiP7pMSixceV9yq2qv7tVHOX8dWV1feoDzd6HW4wvtMso3d+XX7U2bnV4VfM8FHCBO7GLoYROG36YnItE/8pd5Vo63GLgnlFa3QUDD0ljc8uPAL8/ju8kWyPU9+oejcdf6K4UoDdomdjKqqXoOPIlBhifJO2CtN09K5WTLsigC9ok4y1nphfS2d8zoyZIkXVaSBqcvSTFGX/KpcTLZV06i4WCjMJHUteSAQr9lSxguY1r1y7n4v4PE2wicfaSdKJA8pzO+rFWwKO5NPdKR7HMPfrwxqgSbW/1/Ro0RZ++h5SXp8H/706qfyQIqh2FnssK8XvMycpJsb/SFhj4MYN8tQ0weB7ys=
